modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
[[mods]]
modId="redstonemagic"
version="${file.jarVersion}"
displayName="Redstone Magic"
displayURL="https://www.curseforge.com/minecraft/mc-mods/redstone-magic"
updateJSONURL="https://github.com/mactso/RedstoneMagic/raw/master/update.json"
logoFile="logo.png"
authors="MacTso, Lupicus"
description='''Redstone Magic.'''
[[dependencies.redstonemagic]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.redstonemagic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
