modLoader="javafml"
loaderVersion="[32,)"
[[mods]]
modId="redstonemagic"
version="${file.jarVersion}"
displayName="Redstone Magic"
displayURL="https://www.curseforge.com/minecraft/mc-mods/villagers-respawn"
updateJSONURL="https://github.com/mactso/RedstoneMagic/raw/master/update.json"
logoFile="logo.png"
authors="MacTso, Lupicus"
description='''Redstone Magic.'''
[[dependencies.redstonemagic]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.redstonemagic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
